post_writing:
  description: >
    Review the {theme} to ensure the post aligns with its overarching message.
    Focus on the {title} and {summary} to guide the tone and direction of the post.
    
    Write the Post:
    Create a caption that highlights the day’s subject in an engaging and relatable tone.
    Integrate the research from sources seamlessly into the caption to enhance credibility.
    Ensure the post ties back to the weekly theme and creates a cohesive narrative with other posts for the week.
    Include a call-to-action (e.g., asking questions, inviting comments, or encouraging sharing).

    Generate Hashtags:
    Identify 15–20 hashtags relevant to the post’s content and the weekly theme.
    Use a mix of popular, niche, and branded hashtags to maximize visibility and attract the target audience.

  expected_output: >
    You will return the output in a json file.  The file will be well-structured and will have the format:
    DayOfTheWeek: str - this is the {DayOfTheWeek} for the post.
    title: str which will be {title}
    summary: str which will be {summary}
    sources: str which will be {sources}
    posttext: str this will be the post that you create for the day of the week
    Hashtags: List[str] which will be the list of hashtags for the post.
  agent: content_writer

# prompt_writing:
#   description: >
#     Find relevant and impactful leadership quotes and verify their authenticity based on the outline that you will be provided.  You are to provide content for the posts, 
#     but you do not have to worry about writing the final posts. The content needs to match the theme for the week.  You will need to include sources so they can be verified.  
#   expected_output: >
#     A thorough outline of a plan for leadership Instagram posts.  The plan should be detailed enough where someone can research each theme and post title. 
#     The plan should follow the following format:
#     Theme for the week: str - this will be the theme for the week and the posts will be shaped around the theme
#     Then an array of weekdays:
#         DaysOfTheWeek: str - This will be the day of the week for the post, it can only be Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, or Sunday.
#         title: str - This will be the title of the post (e.g. How to be a servant leader).
#         sources: List[str] - This will be a list of the sources and where they are located.  If you used a web page then you need to list the URL here.
#
#     YOU MUST MATCH THE THEME OF THE WEEK and must have a post for each day of the week.
#   agent: AI_prompt_engineer

